// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://glnxmnzcsbtbjyhltvzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdsbnhtbnpjc2J0Ymp5aGx0dnpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNTM3NjksImV4cCI6MjA2NzcyOTc2OX0.KP_Z7c2sEmeJlM7QGQaQIL1iq2ZRXiGZoT1dc55mGuw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});